name: Plugin Check

'on':
  push:
  pull_request:

jobs:
  plugin-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Plugin Check
        uses: wordpress/plugin-check-action@v1
        with:
          slug: all-the-content-changes
          exclude-files: |
            .gitignore
            phpcs.xml.dist
            phpunit.xml.dist
          exclude-directories: |
            .git
            .github
            build
            tests
            vendor
            node_modules
